use_frameworks!

target 'EHItemsView_Example' do
  pod 'EHItemsView', :path => '../'
  pod 'Masonry', '~> 0.6.4'
  pod 'YYCategories', '~> 1.0.1'

  target 'EHItemsView_Tests' do
    inherit! :search_paths

    
  end
end
